"""Add expanded gamification, missions, challenges, marketplace, and social features

Revision ID: f3fc7b8669ac
Revises: 
Create Date: 2025-11-18 05:57:48.237321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fc7b8669ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gamification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('selected_theme', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gamification', schema=None) as batch_op:
        batch_op.drop_column('selected_theme')
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###
